### ISSUE TITLE
Python 2 - "TypeError: message() takes exactly 3 arguments (4  given)"

### ISSUE THREAD

**Issue by glowingsteam** [adafruit/io-client-python#38]
Library works fine on python3, but has the error in the title when using Python 2. I don't know if I am missing dependencies, but I just wanted to let you all know. :)

**Comment by h-c-c** [comment]
Just wanted to chime in, I'm also seeing this.  I'm relegated to Python 2 in a project since the Adafruit_DotStar_Pi module is Python 2 only.  

I did this as a workaround:
https://github.com/adafruit/io-client-python/blob/master/Adafruit_IO/mqtt_client.py#L95

`--            self.on_message(self, feed, payload, retain)`
`++           self.on_message(self, feed, payload)`

**Comment by brentru** [comment]
@h-c-c We're going to limit this library to Python 3.6+. I'll add that as a suggested workaround for those who are using older Python2-Only libraries. Thanks!
